// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektSchronisko.AppData;

namespace ProjektSchronisko.Migrations
{
    [DbContext(typeof(AnimalsContext))]
    [Migration("20210520143012_InitAnimalsDB")]
    partial class InitAnimalsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjektSchronisko.Models.Animal", b =>
                {
                    b.Property<Guid>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RaceAnimal")
                        .HasColumnType("int");

                    b.Property<int>("TypeAnimale")
                        .HasColumnType("int");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
