// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektSchronisko.AppData;

namespace ProjektSchronisko.Migrations
{
    [DbContext(typeof(AnimalsContext))]
    [Migration("20210523201528_addPhotoURLtoAnimals")]
    partial class addPhotoURLtoAnimals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjektSchronisko.Models.Animal", b =>
                {
                    b.Property<Guid>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPathURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceAnimal")
                        .HasColumnType("int");

                    b.Property<int>("TypeAnimale")
                        .HasColumnType("int");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ProjektSchronisko.Models.ReportAnimal", b =>
                {
                    b.Property<Guid>("IdReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeReport")
                        .HasColumnType("int");

                    b.HasKey("IdReport");

                    b.ToTable("ReportAnimal");
                });
#pragma warning restore 612, 618
        }
    }
}
